# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  terraformVersion: 0.12.9


stages:
  - stage: CI
    displayName: CI - Terraform test
    jobs:
    - template: pipeline/steps/01-config-check.yml
      parameters:
        terraformVersion: $(terraformVersion)