# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  terraformVersion: 0.12.9

stages:
  - stage: ci_config_check
    displayName: CI - Terraform test
    jobs:
    - template: pipeline/steps/01-config-check.yml
      parameters:
        terraformVersion: ${{ variables.terraformVersion }}
  
  - stage: terraform_init
    displayName: CI - Terraform init
    dependsOn: ci_config_check
    condition: succeeded('ci_config_check')
    jobs:
    - template: pipeline/steps/10-terraform-init.yml
      parameters:
        terraformVersion: ${{ variables.terraformVersion }}
        environment: 'sbox-hmi'
        subscription: DTS-SHAREDSERVICES-SBOX
        resourcegroup: azure-devops-test
        storageaccount: azuredevopstestsa