# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - azure-pipelines-ci
  paths:
    exclude:
      - .git
      - .gitignore
      - README.md

variables:
  terraformVersion: 0.12.9

stages:
  - stage: ci_config_check
    displayName: CI - Config Check
    jobs:
    - template: pipeline/steps/01-config-check.yml
      parameters:
        terraformVersion: ${{ variables.terraformVersion }}


  - stage: terraform_sbox
    displayName: CI - Terraform SandBox
    dependsOn: ci_config_check
    condition: succeeded('ci_config_check')
    jobs:
    - template: pipeline/steps/10-terraform.yml
      parameters:
        terraformVersion: ${{ variables.terraformVersion }}
        environment: 'sbox-hmi'
        subscription: DTS-SHAREDSERVICES-SBOX #DTS-HMI-SBOX
        resourcegroup: azure-devops-test #rg-HMIv1
        storageaccount: azuredevopstestsa
  
  - stage: create_artifacts
    displayName: CI - Create Artifact
    dependsOn: ci_config_check
    condition: succeeded('ci_config_check')
    jobs:
    - template: pipeline/steps/02-create-artifact.yml