trigger:
  - master
pr:
  - master
parameters:
  - name: env
    displayName: Env
    type: string
    default: sbox
    values:
      - sbox

variables:
  - template: pipeline/variables-common.yaml
  - ${{ if eq(parameters.env, 'sbox') }}:
      # Sandbox (sbox)
      - template: pipeline/variables-sbox.yaml
      - group: fh-hmi-sbox


stages:
  - stage: Build
    jobs:
      - job: BasicValidation
        steps:
          - template: pipeline/steps/tf-install.yaml
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              commandOptions: '-backend=false'
          - task: TerraformCLI@0
            displayName: Validate Terraform
            inputs:
              command: 'validate'
              commandOptions: '-no-color'
          - script: terraform fmt -check=true
            displayName: Check Formatting

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployToEnv
        steps:

          - template: pipeline/steps/tf-init.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              product: $(product)
              env: $(env)

          - template: pipeline/steps/tf-plan.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              env: $(env)
              product: $(product)

          - template: pipeline/steps/tf-apply.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              env: $(env)